name = "basicauth"
main = "src/index.ts"
compatibility_date = "2022-11-15"
compatibility_flags = [
  "streams_enable_constructors"
]
route = { pattern = "auth.piperswe.me", custom_domain = true }
minify = true

analytics_engine_datasets = [
  { binding = "LOGIN_ANALYTICS", dataset = "basicauth_logins" }
]

[vars]
DOMAIN = "auth.piperswe.me"
ROOT_REDIRECT = "https://piper.cloudflareaccess.com"
NAME = "Piper's Authentication"

[[ kv_namespaces ]]
binding = "AUTHCODES"
id = "f2ab9caadb634c9d81d0b8b26abac732"
preview_id = "90625828892641409c19a11ade8263eb"

[[ kv_namespaces ]]
binding = "CSRF_TOKENS"
id = "b3fc3b45239648d6ad89743047617a2a"
preview_id = "cc606c140bcc46e297a58ac03f4bf05d"

[[ d1_databases ]]
binding = "DB"
database_name = "basicauth"
database_id = "2a8d4d42-212b-4734-98a6-37629978ad71"
preview_database_name = "basicauth-dev"
preview_database_id = "020d5c71-e7ed-41b2-bc87-661f5dbadb8e"

[[ d1_databases ]]
binding = "DB_DEV"
database_name = "basicauth-dev"
database_id = "020d5c71-e7ed-41b2-bc87-661f5dbadb8e"
preview_database_name = "basicauth-dev"
preview_database_id = "020d5c71-e7ed-41b2-bc87-661f5dbadb8e"
